workflows:
  android-release:
    name: ChessMotion Android Release
    max_build_duration: 60
    environment:
      flutter: 3.24.5
      java: 17 # Java 17 zyada stable hai Flutter 3.24 ke liye
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build release APK
        script: |
          # Clean purana build
          flutter clean
          # Simple release build bina extra flags ke taaki error na aaye
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - rekhaji7172@gmail.com
